python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 0 --test 1000  --epochs 1
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 1 --test 1000  --epochs 1 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 1 --test 1000  --epochs 3 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 1 --test 1000  --epochs 5 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 2 --test 1000  --epochs 1 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 2 --test 1000  --epochs 3 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 2 --test 1000  --epochs 5 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 3 --test 1000  --epochs 1 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 3 --test 1000  --epochs 3 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 3 --test 1000  --epochs 5 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 4 --test 1000  --epochs 1 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 4 --test 1000  --epochs 3 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 4 --test 1000  --epochs 5 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 5 --test 1000  --epochs 1 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 5 --test 1000  --epochs 3 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 5 --test 1000  --epochs 5 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 10 --test 1000  --epochs 1 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 10 --test 1000  --epochs 3 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 10 --test 1000  --epochs 5 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 20 --test 1000  --epochs 1 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 20 --test 1000  --epochs 3 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 20 --test 1000  --epochs 5 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 50 --test 1000  --epochs 1 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 50 --test 1000  --epochs 3 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 50 --test 1000  --epochs 5 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 100 --test 1000  --epochs 1 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 100 --test 1000  --epochs 3 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 100 --test 1000  --epochs 5 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 1000 --test 1000  --epochs 1 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 1000 --test 1000  --epochs 3 --tune
python naive_ranker_test.py --hotpot ~/data/hotpot_train_v1.1.json --train 1000 --test 1000  --epochs 5 --tune
